# Numpy exercises for training

Source: [link](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

**1. Import numpy as np and see the version**

In [3]:
import numpy as np

np.version.version

'1.19.1'

**2. How to create a 1D array?**

In [6]:
my_first_array = np.array(np.arange(1,10,2))
my_first_array

array([1, 3, 5, 7, 9])

**3. How to create a boolean array?**

In [10]:
boolean_array_v1 = np.array([True, False, True])
boolean_array_v1

array([ True, False,  True])

In [12]:
boolean_array_v2 = np.array(['a', ', ', None, False, True, 0], dtype=bool)
boolean_array_v2

array([ True,  True, False, False,  True, False])

**4. How to extract items that satisfy a given condition from 1D array?**

Extract all odd numbers from `arr`

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

**5. How to replace items that satisfy a condition with another value in numpy array?**

Replace all odd numbers in `arr` with -1

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[arr % 2 == 1] = -1

In [24]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6. How to replace items that satisfy a condition without affecting the original array?**

Replace all odd numbers in `arr` with -1 without changing `arr`

In [33]:
arr = np.arange(10)
arr2 = np.where(arr % 2 == 1, -1, arr)
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**7. How to reshape an array?**


Obs: Then, in a `numpy` array, the entire array is inside a `[]`, having as elements other `[]`'s as rows. Then, each dimension is one `[]`

In [34]:
arr = np.arange(10)

In [35]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
arr.reshape(1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
arr.reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

**8. How to stack two arrays vertically?**

Obs
* Concatenate = arrange the two arrays in order to make a bigger one
* Stack = literally stack the two arrays. If needed, creates a new dimension in order to do that
    * Ex:
    ```python
    >> a = np.arange(5)
    >> b = np.arange(5)
    >> a_r = a.reshape(1, -1)
    >> b_r = b.reshape(1, -1)
    >> np.hstack((a,b)).shape
    (10,)
    >> np.stack((a_r, b_r), axis=0).shape
    (2,1,5)
    >> np.stack((a_r, b_r), axis=1).shape
    (1,2,5)
    ```

In [149]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1,10).reshape(2, -1)

In [154]:
np.concatenate((a,b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**9. How to stack two arrays horizontally?**

In [155]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [158]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**10. How to generate custom sequences in numpy without hardcoding?**

In [159]:
a = np.array([1,2,3])

In [189]:
np.r_[np.concatenate([np.repeat(i, 3) for i in range(1,4)]), np.tile(np.arange(1,4), 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])